-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 18:48:55 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema matcha_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema matcha_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `matcha_DB` DEFAULT CHARACTER SET utf8 ;
USE `matcha_DB` ;

-- -----------------------------------------------------
-- Table `matcha_DB`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matcha_DB`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `username` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `salt` VARCHAR(255) NULL,
  `sexe` ENUM('man', 'woman') NULL,
  `bio` MEDIUMTEXT NULL,
  `orientation` ENUM('men', 'women', 'both') NULL,
  `confirmkey` VARCHAR(255) NULL,
  `activate` INT NULL DEFAULT 0,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `blocked` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matcha_DB`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matcha_DB`.`likes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `user_liked_id` INT NOT NULL,
  `user_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id1`),
  INDEX `fk_likes_user_idx` (`user_id1` ASC),
  CONSTRAINT `fk_likes_user`
    FOREIGN KEY (`user_id1`)
    REFERENCES `matcha_DB`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matcha_DB`.`pictures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matcha_DB`.`pictures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id1`),
  INDEX `fk_pictures_user1_idx` (`user_id1` ASC),
  CONSTRAINT `fk_pictures_user1`
    FOREIGN KEY (`user_id1`)
    REFERENCES `matcha_DB`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matcha_DB`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matcha_DB`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matcha_DB`.`user_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matcha_DB`.`user_has_tags` (
  `user_id` INT NOT NULL,
  `tags_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `tags_id`),
  INDEX `fk_user_has_tags_tags1_idx` (`tags_id` ASC),
  INDEX `fk_user_has_tags_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_tags_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `matcha_DB`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `matcha_DB`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matcha_DB`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matcha_DB`.`location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `latitude` DECIMAL(10,8) NULL,
  `longitude` DECIMAL(11,8) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matcha_DB`.`location_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matcha_DB`.`location_has_user` (
  `location_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`location_id`, `user_id`),
  INDEX `fk_location_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_location_has_user_location1_idx` (`location_id` ASC),
  CONSTRAINT `fk_location_has_user_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `matcha_DB`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_location_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `matcha_DB`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
